version: '3'

services:
  app:
    env_file:
      - .env
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
  telegram-bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always

volumes:
  db: